### ISSUE TITLE
Decorazione momenti

### ISSUE THREAD

**Issue by mcamurri** [franen/matrita#1]
Ciao Francesco,
grazie per aver creato il pacchetto matrita, è molto ben fatto. Sto cercando di inserire una decorazione di default prima del titolo dei momenti. Ho provato con:

```
\newcommand{\momento}[1]{%
 {\par\vspace{\premomentoskip}%
 \noindent\Large\maiuscolettospaziato{\aldineleft#1}}%
 \par\nobreak\bigskip%
}
```

Ma in fase di compilazione ricevo `encoding scheme``u' unknown`.

Lo stesso accade se provo a mettere la decorazione direttamente nel titolo del documento.

**Comment by franen** [comment]
I glifi di fourier orns non sono  compatibili con il pacchetto textcase (del resto perché dovrebbero esserlo? :-) ). La soluzione è lasciare i glifi fuori dall'argomento di \maiuscolettospaziato:
`\noindent\Large\aldineleft{} \maiuscolettospaziato{#1}}%`
